# Generated by Django 5.2.7 on 2025-11-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, unique=True, verbose_name='Секция')),
                ('title_kr', models.CharField(max_length=200, verbose_name='Заголовок корейский')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок русский')),
                ('content_ru', models.TextField(verbose_name='Текст русский')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контент меню',
                'verbose_name_plural': 'Контент меню',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.PositiveIntegerField(default=50, verbose_name='Общее количество мест')),
                ('max_guests_per_booking', models.PositiveIntegerField(default=10, verbose_name='Максимум гостей в одном бронировании')),
            ],
            options={
                'verbose_name': 'Вместимость ресторана',
                'verbose_name_plural': 'Вместимость ресторана',
            },
        ),
    ]
